version: '3.1'

services:
  # Traefik reverse proxy with the modifier plugin
  traefik:
    image: traefik:v3.1
    container_name: traefik-modifier
    command:
      - --configFile=/etc/traefik/traefik.yaml
    ports:
      - "8000:8000"     # HTTP entry point
      - "8080:8080"     # Traefik dashboard
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - .:/plugins-local/src/github.com/hukumonline-com/traefik-modifier:ro
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"

  # Chat service - for testing request/response masking
  chat-service:
    image: node:18-alpine
    container_name: chat-service
    working_dir: /app
    volumes:
      - ./docker/package.json:/app/package.json
      - ./docker/test-backend.js:/app/test-backend.js
    command: >
      sh -c "npm install && node test-backend.js"
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.localhost`)"
      - "traefik.http.routers.chat.service=chat-service"
      - "traefik.http.services.chat-service.loadbalancer.server.port=3000"
      - "traefik.http.routers.chat.middlewares=chat-modifier"

networks:
  traefik-network:
    driver: bridge